services:
  psql_server:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${PG_DB_DATABASE}
      POSTGRES_USER: ${PG_DB_USERNAME}
      POSTGRES_PASSWORD: ${PG_DB_PASSWORD}
    ports:
      - "${PG_DB_PORT}:5432"
    volumes:
      - psql_volume_bp:/var/lib/postgresql/data

volumes:
  psql_volume_bp:
